name: tag

on:
  release:
    types: [published]

jobs:
  tag:
    name: Tag capa rules
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout capa-rules
      uses: actions/checkout@v2
      with:
        repository: fireeye/capa-rules
        token: ${{ secrets.CAPA_TOKEN }}
    - name: Tag capa-rules
      run: git tag ${{ github.event.release.tag_name }}
    - name: Push tag to capa-rules
      uses: ad-m/github-push-action@master
      with:
        repository: fireeye/capa-rules
        github_token: ${{ secrets.CAPA_TOKEN }}
        tags: true
